[workspace]
members  = ["packages/app", "packages/game_domain"]
resolver = "3"

[workspace.package]
authors    = ["Braden Steffaniak"]
edition    = "2024"
license    = "MPL-2.0"
readme     = "README.md"
repository = "https://github.com/bradenst/wwmtf"
version    = "0.1.0"

[workspace.dependencies]
argon2 = { version = "0.5.3", default-features = false, features = [
    "alloc",
    "password-hash",
    "rand",
] }
async-lock = { version = "3.4.2", default-features = false }
async-trait = { version = "0.1.89", default-features = false }
base64 = { version = "0.23.1", default-features = false, features = ["std"] }
env_logger = { version = "0.11.11", default-features = false, features = [
    "auto-color",
    "humantime",
] }
flume = { version = "0.12.0", default-features = false, features = ["async"] }
futures-lite = { version = "2.6.1", default-features = false, features = [
    "std",
] }
hyperchad = { git = "https://github.com/MoosicBox/MoosicBox.git", rev = "c4d2e8f11fc703d50c8ac283aaa2028bfec231c9", default-features = false }
image = { version = "0.25.10", default-features = false, features = [
    "jpeg",
    "png",
    "webp",
] }
log = { version = "0.4.33", default-features = false, features = [
    "release_max_level_trace",
] }
openidconnect = { version = "4.0.1", default-features = false, features = [
    "reqwest",
    "rustls-tls",
] }
proptest = { version = "1.11.0", default-features = false, features = ["std"] }
rand_core = { version = "0.6.4", default-features = false, features = [
    "getrandom",
] }
reqwest = { version = "0.13.4", default-features = false, features = [
    "json",
    "rustls",
] }
serde = { version = "1.0.229", default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0.151", default-features = false, features = [
    "std",
] }
sha2 = { version = "0.11.0", default-features = false }
switchy_database = { git = "https://github.com/MoosicBox/MoosicBox.git", branch = "master", default-features = false }
switchy_database_connection = { git = "https://github.com/MoosicBox/MoosicBox.git", branch = "master", default-features = false }
switchy_schema = { git = "https://github.com/MoosicBox/MoosicBox.git", branch = "master", default-features = false }
thiserror = { version = "2.0.19", default-features = false }
time = { version = "0.3.54", default-features = false, features = [
    "serde",
    "std",
] }
tokio = { version = "1.53.1", default-features = false, features = [
    "net",
    "rt",
    "rt-multi-thread",
    "time",
] }
uuid = { version = "1.24.0", default-features = false, features = [
    "serde",
    "v4",
] }
wwmtf_game_domain = { path = "packages/game_domain" }
